# 워크플로우 이름
name: Deploy To EC2

on:
  # 어떤 작업할 때 실행할 지 (main이라는 브랜치가 푸시될 때)
  push:
    branches:
      - main

jobs:
  # job의 이름 (Deloy라 지정했음)
  Deloy:
    # 어떤 운영체제에서 실행되는지
    runs-on: ubuntu-latest
    # 작업 단계들
    steps:
      - name: SSH(원격 접속)로 EC2에 접속하기
        # (일일히 다 쳐도 되지만) 어떤 라이브러리쓸거냐? https://github.com/marketplace/actions/ssh-remote-commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_Host }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: | # 여러 명령어 쓸땐 이런식으로 쓰라고 공식문서에 나와있음 / 4번째 줄. 돌고 있는 8080 서버가 없으면 에러로 인식돼서 || true 추가
            cd /home/ubuntu/ImageUpload-S3
            git pull origin main
            ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1
            
